/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/users/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Gets the current authenticated user's information */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns user information */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['UserResponse'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/**
		 * Permanently deletes the current authenticated user's account.
		 *     Requires password confirmation. Revokes all tokens and clears auth cookies.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The account deletion request containing the user's password */
			requestBody: {
				content: {
					'application/json': components['schemas']['DeleteAccountRequest'];
				};
			};
			responses: {
				/** @description Account successfully deleted */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the password is incorrect or the request is invalid */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		/** Updates the current authenticated user's profile information */
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The profile update request */
			requestBody: {
				content: {
					'application/json': components['schemas']['UpdateUserRequest'];
				};
			};
			responses: {
				/** @description Returns updated user information */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['UserResponse'];
					};
				};
				/** @description If the request is invalid */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		trace?: never;
	};
	'/api/auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Authenticates a user and returns JWT tokens.
		 *     Tokens are always returned in the response body. When useCookies is true, tokens are also set as HttpOnly cookies.
		 */
		post: {
			parameters: {
				query?: {
					/** @description When true, sets tokens in HttpOnly cookies for web clients. Defaults to false (stateless). */
					useCookies?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The login credentials */
			requestBody: {
				content: {
					'application/json': components['schemas']['LoginRequest'];
				};
			};
			responses: {
				/** @description Returns authentication tokens (optionally also set in HttpOnly cookies) */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AuthenticationResponse'];
					};
				};
				/** @description If the credentials are improperly formatted */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the credentials are invalid */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Refreshes the authentication tokens using a refresh token.
		 *     For web clients, the refresh token is read from cookies. For mobile/API clients, pass it in the request body.
		 *     When useCookies is true, new tokens are also set as HttpOnly cookies.
		 */
		post: {
			parameters: {
				query?: {
					/** @description When true, sets tokens in HttpOnly cookies for web clients. Defaults to false (stateless). */
					useCookies?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Optional request body containing the refresh token (for mobile/API clients) */
			requestBody?: {
				content: {
					'application/json': null | components['schemas']['RefreshRequest'];
				};
			};
			responses: {
				/** @description Returns new authentication tokens (optionally also set in HttpOnly cookies) */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AuthenticationResponse'];
					};
				};
				/** @description If the request body is malformed */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the refresh token is invalid, expired, or missing */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Logs out the current user by revoking refresh tokens and clearing authentication cookies. */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Successfully logged out */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Registers a new user account */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The registration details */
			requestBody: {
				content: {
					'application/json': components['schemas']['RegisterRequest'];
				};
			};
			responses: {
				/** @description User successfully created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['RegisterResponse'];
					};
				};
				/** @description If the registration data is invalid */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If too many registration requests have been made */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/forgot-password': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Initiates a password reset flow by sending a reset link to the provided email address.
		 *     Always returns 200 regardless of whether the email exists to prevent user enumeration.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The forgot password request containing the email address */
			requestBody: {
				content: {
					'application/json': components['schemas']['ForgotPasswordRequest'];
				};
			};
			responses: {
				/** @description Request accepted (email sent if account exists) */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the request is invalid */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If too many requests have been made */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/reset-password': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Resets a user's password using a token received via email.
		 *     Revokes all existing refresh tokens to force re-authentication on other devices.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The reset password request containing email, token, and new password */
			requestBody: {
				content: {
					'application/json': components['schemas']['ResetPasswordRequest'];
				};
			};
			responses: {
				/** @description Password reset successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the request is invalid or the token is expired/invalid */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If too many requests have been made */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/verify-email': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Verifies a user's email address using a confirmation token received via email. */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The email verification request containing email and token */
			requestBody: {
				content: {
					'application/json': components['schemas']['VerifyEmailRequest'];
				};
			};
			responses: {
				/** @description Email verified successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the request is invalid or the token is expired/invalid */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If too many requests have been made */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/resend-verification': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Resends a verification email to the current authenticated user.
		 *     Fails if the user's email is already verified.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Verification email sent */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the email is already verified */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If too many requests have been made */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/change-password': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Changes the current authenticated user's password.
		 *     Revokes all existing refresh tokens to force re-authentication on other devices.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The change password request containing current and new passwords */
			requestBody: {
				content: {
					'application/json': components['schemas']['ChangePasswordRequest'];
				};
			};
			responses: {
				/** @description Password changed successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the request is invalid or the current password is incorrect */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Gets a paginated list of all users, optionally filtered by a search term. */
		get: {
			parameters: {
				query?: {
					/** @description Optional search term to filter users by name or email. */
					search?: string;
					/** @description The page number to retrieve (1-based). */
					pageNumber?: number;
					/** @description The number of items per page (maximum 100). */
					pageSize?: number;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns the paginated user list */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ListUsersResponse'];
					};
				};
				/** @description If the pagination parameters are invalid */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		/** Creates a new user account and sends an invitation email with a password reset link. */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The user creation request containing email and optional name fields */
			requestBody: {
				content: {
					'application/json': components['schemas']['CreateUserRequest'];
				};
			};
			responses: {
				/** @description User created successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the email is already taken or validation fails */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/users/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Gets a single user by ID with full admin-level details. */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The user ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns the user details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AdminUserResponse'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/**
		 * Permanently deletes a user account. The caller must outrank the target user
		 *     and cannot delete themselves or the last user with an administrative role.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The user ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User deleted successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the delete operation failed or hierarchy check fails */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/users/{id}/roles': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Assigns a role to a user. The caller must outrank the target user
		 *     and can only assign roles below their own rank.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The user ID */
					id: string;
				};
				cookie?: never;
			};
			/** @description The role to assign */
			requestBody: {
				content: {
					'application/json': components['schemas']['AssignRoleRequest'];
				};
			};
			responses: {
				/** @description Role assigned successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the role is invalid, the user already has it, or hierarchy check fails */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/users/{id}/roles/{role}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Removes a role from a user. The caller must outrank the target user
		 *     and cannot remove roles at or above their own rank.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The user ID */
					id: string;
					/** @description The role name to remove */
					role: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Role removed successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the role is invalid, the user doesn't have it, or hierarchy check fails */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/users/{id}/lock': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Locks a user account, preventing login. The caller must outrank the target user
		 *     and cannot lock themselves.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The user ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User locked successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the lock operation failed or hierarchy check fails */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/users/{id}/unlock': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Unlocks a user account, allowing login. The caller must outrank the target user. */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The user ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User unlocked successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the unlock operation failed or hierarchy check fails */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/users/{id}/verify-email': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Manually verifies a user's email address. The caller must outrank the target user. */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The user ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Email verified successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the email is already verified or hierarchy check fails */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/users/{id}/send-password-reset': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sends a password reset email to a user on behalf of an admin.
		 *     The caller must outrank the target user.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The user ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Password reset email sent successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the hierarchy check fails */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/roles': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Gets all roles with user counts. */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns the list of roles */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AdminRoleResponse'][];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		/** Creates a new custom role. */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The role name and optional description */
			requestBody: {
				content: {
					'application/json': components['schemas']['CreateRoleRequest'];
				};
			};
			responses: {
				/** @description Role created successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the role name is taken or validation fails */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/roles/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Gets detailed information about a single role, including its permissions and user count. */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The role ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns the role details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['RoleDetailResponse'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the role was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		/** Updates an existing role's name and/or description. System roles cannot be renamed. */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The role ID */
					id: string;
				};
				cookie?: never;
			};
			/** @description The fields to update */
			requestBody: {
				content: {
					'application/json': components['schemas']['UpdateRoleRequest'];
				};
			};
			responses: {
				/** @description Role updated successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the update is invalid (system role rename, name taken, etc.) */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the role was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		post?: never;
		/** Deletes a custom role. System roles and roles with assigned users cannot be deleted. */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The role ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Role deleted successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the role is a system role or has users assigned */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the role was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/roles/{id}/permissions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Replaces all permissions on a role. Rotates security stamps for affected users.
		 *     SuperAdmin permissions cannot be modified.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The role ID */
					id: string;
				};
				cookie?: never;
			};
			/** @description The new set of permissions */
			requestBody: {
				content: {
					'application/json': components['schemas']['SetPermissionsRequest'];
				};
			};
			responses: {
				/** @description Permissions updated successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the permissions are invalid or SuperAdmin is targeted */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the role was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/permissions': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Returns all available permissions grouped by category. */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns the permission groups */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['PermissionGroupResponse'][];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/jobs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Gets all registered recurring jobs. */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns the list of recurring jobs */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['RecurringJobResponse'][];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/jobs/{jobId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Gets detailed information about a recurring job, including recent execution history. */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The recurring job identifier */
					jobId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns the job details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['RecurringJobDetailResponse'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the job was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/** Removes a recurring job from the scheduler. */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The recurring job identifier */
					jobId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Job removed successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the job was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If too many requests have been made */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/jobs/restore': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Re-registers all recurring job definitions, restoring any jobs deleted from the dashboard.
		 *     Paused jobs are re-registered with a disabled schedule to preserve their pause state.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Jobs restored successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the restore operation failed */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/jobs/{jobId}/trigger': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Manually triggers an immediate execution of a recurring job. */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The recurring job identifier */
					jobId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Job triggered successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the trigger operation failed */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the job was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/jobs/{jobId}/pause': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Pauses a recurring job by disabling its schedule. */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The recurring job identifier */
					jobId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Job paused successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the job was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If too many requests have been made */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/v1/admin/jobs/{jobId}/resume': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Resumes a previously paused recurring job. */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description The recurring job identifier */
					jobId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Job resumed successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the user does not have the required permission */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If the job was not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description If too many requests have been made */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** @description Represents a role with its associated user count. */
		AdminRoleResponse: {
			/**
			 * Format: uuid
			 * @description The unique identifier of the role.
			 */
			id?: string;
			/** @description The name of the role. */
			name?: string;
			/** @description An optional description of the role's purpose. */
			description?: null | string;
			/** @description Whether this is a system-defined role that cannot be deleted or renamed. */
			isSystem?: boolean;
			/**
			 * Format: int32
			 * @description The number of users assigned to this role.
			 */
			userCount?: number;
			/** @description The permission claim values assigned to this role. */
			permissions?: string[];
		};
		/** @description Represents a user's full profile and account details for admin views. */
		AdminUserResponse: {
			/**
			 * Format: uuid
			 * @description The unique identifier of the user.
			 */
			id?: string;
			/** @description The username of the user (same as email). */
			username?: string;
			/** @description The email address of the user. */
			email?: string;
			/** @description The first name of the user. */
			firstName?: null | string;
			/** @description The last name of the user. */
			lastName?: null | string;
			/** @description The phone number of the user. */
			phoneNumber?: null | string;
			/** @description A short biography or description of the user. */
			bio?: null | string;
			/** @description The URL to the user's avatar image. */
			avatarUrl?: null | string;
			/** @description The roles assigned to the user. */
			roles?: string[];
			/** @description Whether the user's email address has been confirmed. */
			emailConfirmed?: boolean;
			/** @description Whether lockout is enabled for this user. */
			lockoutEnabled?: boolean;
			/**
			 * Format: date-time
			 * @description When the lockout ends, or null if the user is not locked out.
			 */
			lockoutEnd?: null | string;
			/**
			 * Format: int32
			 * @description The number of consecutive failed login attempts.
			 */
			accessFailedCount?: number;
			/** @description Whether the user is currently locked out. */
			isLockedOut?: boolean;
		};
		/** @description Request to assign a role to a user. */
		AssignRoleRequest: {
			/** @description The name of the role to assign. */
			role: string;
		};
		/**
		 * @description Response containing authentication tokens for API clients.
		 *     Web clients can ignore this response body as tokens are also set in HttpOnly cookies.
		 */
		AuthenticationResponse: {
			/**
			 * @description The JWT access token for Bearer authentication.
			 *     Include this in the Authorization header as "Bearer {accessToken}" for subsequent API requests.
			 */
			accessToken?: string;
			/**
			 * @description The refresh token for obtaining new access tokens.
			 *     Use this with the /api/auth/refresh endpoint when the access token expires.
			 */
			refreshToken?: string;
		};
		/** @description Represents a request to change the current user's password. */
		ChangePasswordRequest: {
			/** @description The user's current password for verification. */
			currentPassword: string;
			/** @description The new password to set for the account. */
			newPassword: string;
		};
		/** @description Request to create a new custom role. */
		CreateRoleRequest: {
			/** @description The name of the new role. */
			name: string;
			/** @description An optional description of the role's purpose. */
			description?: null | string;
		};
		/** @description Request to create a new user account via admin invitation. */
		CreateUserRequest: {
			/** @description The email address of the user to invite. */
			email: string;
			/** @description An optional first name for the new user. */
			firstName?: null | string;
			/** @description An optional last name for the new user. */
			lastName?: null | string;
		};
		/** @description Represents a request to permanently delete the current user's account. */
		DeleteAccountRequest: {
			/** @description The user's current password for confirmation. */
			password: string;
		};
		/** @description Represents a request to initiate a password reset flow. */
		ForgotPasswordRequest: {
			/** @description The email address associated with the account. */
			email: string;
		};
		/** @description Represents a single job execution history entry. */
		JobExecutionResponse: {
			/** @description The background job identifier for this execution. */
			jobId?: string;
			/** @description The execution status (e.g. "Succeeded", "Failed", "Processing"). */
			status?: string;
			/**
			 * Format: date-time
			 * @description When the execution started.
			 */
			startedAt?: null | string;
			/** @description How long the execution took, or null if still running. */
			duration?: null | string;
			/** @description The error message if the execution failed, or null on success. */
			error?: null | string;
		};
		/** @description Paginated response containing a list of admin user records. */
		ListUsersResponse: {
			/** @description The users for the current page. */
			items?: components['schemas']['AdminUserResponse'][];
			/**
			 * Format: int32
			 * @description The total number of items (across all pages).
			 */
			totalCount?: number;
			/**
			 * Format: int32
			 * @description The current page number.
			 */
			pageNumber?: number;
			/**
			 * Format: int32
			 * @description The number of items per page.
			 */
			pageSize?: number;
			/**
			 * Format: int32
			 * @description The total number of pages.
			 */
			totalPages?: number;
			/** @description Indicates if there is a previous page. */
			hasPreviousPage?: boolean;
			/** @description Indicates if there is a next page. */
			hasNextPage?: boolean;
		};
		/** @description Represents a user login request with credentials. */
		LoginRequest: {
			/** @description The username for authentication. */
			username: string;
			/** @description The password for authentication. */
			password: string;
			/**
			 * @description When true, authentication cookies persist across browser restarts.
			 *     When false (default), session cookies are used and expire when the browser closes.
			 */
			rememberMe?: boolean;
		};
		/** @description A group of permissions belonging to the same category. */
		PermissionGroupResponse: {
			/** @description The category name (e.g. "Users", "Roles"). */
			category?: string;
			/** @description The permission values in this category. */
			permissions?: string[];
		};
		ProblemDetails: {
			type?: null | string;
			title?: null | string;
			/** Format: int32 */
			status?: null | number;
			detail?: null | string;
			instance?: null | string;
		};
		/** @description Detailed recurring job response including execution history. */
		RecurringJobDetailResponse: {
			/** @description The unique job identifier. */
			id?: string;
			/** @description The cron expression for the job schedule. */
			cron?: string;
			/**
			 * Format: date-time
			 * @description The next scheduled execution time, or null if paused.
			 */
			nextExecution?: null | string;
			/**
			 * Format: date-time
			 * @description The last execution time, or null if never executed.
			 */
			lastExecution?: null | string;
			/** @description The status of the most recent execution. */
			lastStatus?: null | string;
			/** @description Whether the job is currently paused. */
			isPaused?: boolean;
			/**
			 * Format: date-time
			 * @description When the job was registered.
			 */
			createdAt?: null | string;
			/** @description Recent execution history entries. */
			executionHistory?: components['schemas']['JobExecutionResponse'][];
		};
		/** @description Represents a recurring job summary for list views. */
		RecurringJobResponse: {
			/** @description The unique job identifier. */
			id?: string;
			/** @description The cron expression for the job schedule. */
			cron?: string;
			/**
			 * Format: date-time
			 * @description The next scheduled execution time, or null if paused.
			 */
			nextExecution?: null | string;
			/**
			 * Format: date-time
			 * @description The last execution time, or null if never executed.
			 */
			lastExecution?: null | string;
			/** @description The status of the most recent execution. */
			lastStatus?: null | string;
			/** @description Whether the job is currently paused. */
			isPaused?: boolean;
			/**
			 * Format: date-time
			 * @description When the job was registered.
			 */
			createdAt?: null | string;
		};
		/**
		 * @description Request to refresh authentication tokens using a refresh token.
		 *     For web clients using cookies, this request body is optional.
		 *     For mobile/API clients, the refresh token must be provided in the request body.
		 */
		RefreshRequest: {
			/**
			 * @description The refresh token obtained from a previous login or refresh response.
			 *     Required for mobile/API clients. Optional for web clients (will fall back to cookie).
			 */
			refreshToken?: null | string;
		};
		/** @description Represents a request to register a new user account. */
		RegisterRequest: {
			/** @description The email address for the new account. */
			email: string;
			/** @description The password for the new account. */
			password: string;
			/** @description The phone number for the new account. */
			phoneNumber?: null | string;
			/** @description The first name of the user. */
			firstName?: null | string;
			/** @description The last name of the user. */
			lastName?: null | string;
		};
		/** @description Represents the response returned after successful user registration. */
		RegisterResponse: {
			/**
			 * Format: uuid
			 * @description The unique identifier of the newly created user.
			 */
			id?: string;
		};
		/** @description Represents a request to reset a password using a token. */
		ResetPasswordRequest: {
			/** @description The email address associated with the account. */
			email: string;
			/** @description The password reset token received via email. */
			token: string;
			/** @description The new password to set. */
			newPassword: string;
		};
		/** @description Detailed role response including permissions and user count. */
		RoleDetailResponse: {
			/**
			 * Format: uuid
			 * @description The unique identifier of the role.
			 */
			id?: string;
			/** @description The name of the role. */
			name?: string;
			/** @description An optional description of the role's purpose. */
			description?: null | string;
			/** @description Whether this is a system-defined role that cannot be deleted or renamed. */
			isSystem?: boolean;
			/** @description The permission claim values assigned to this role. */
			permissions?: string[];
			/**
			 * Format: int32
			 * @description The number of users assigned to this role.
			 */
			userCount?: number;
		};
		/** @description Request to replace all permissions on a role. */
		SetPermissionsRequest: {
			/** @description The full set of permission values to assign to the role. */
			permissions: string[];
		};
		/** @description Request to update an existing role's name and/or description. */
		UpdateRoleRequest: {
			/** @description The new role name, or `null` to keep the current name. */
			name?: null | string;
			/** @description The new description, or `null` to keep the current description. */
			description?: null | string;
		};
		/** @description Represents a request to update the user's profile information. */
		UpdateUserRequest: {
			/** @description The first name of the user. */
			firstName?: null | string;
			/** @description The last name of the user. */
			lastName?: null | string;
			/** @description The phone number of the user. */
			phoneNumber?: null | string;
			/** @description A short biography or description of the user. */
			bio?: null | string;
			/**
			 * Format: uri
			 * @description The URL to the user's avatar image.
			 */
			avatarUrl?: null | string;
		};
		/** @description Represents the current user's information. */
		UserResponse: {
			/**
			 * Format: uuid
			 * @description The unique identifier of the user.
			 */
			id?: string;
			/** @description The username of the user (same as email). */
			username?: string;
			/** @description The email address of the user (same as username). */
			email?: string;
			/** @description The first name of the user. */
			firstName?: null | string;
			/** @description The last name of the user. */
			lastName?: null | string;
			/** @description The phone number of the user. */
			phoneNumber?: null | string;
			/** @description A short biography or description of the user. */
			bio?: null | string;
			/** @description The URL to the user's avatar image. */
			avatarUrl?: null | string;
			/** @description The roles assigned to the user. */
			roles?: string[];
			/** @description The atomic permissions granted to the user through their roles. */
			permissions?: string[];
			/** @description Whether the user's email address has been confirmed. */
			emailConfirmed?: boolean;
		};
		/** @description Represents a request to verify an email address using a confirmation token. */
		VerifyEmailRequest: {
			/** @description The email address to verify. */
			email: string;
			/** @description The email confirmation token received via email. */
			token: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
