/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/users/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Gets the current authenticated user's information */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Returns user information */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['UserResponse'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Updates the current authenticated user's profile information */
		patch: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The profile update request */
			requestBody: {
				content: {
					'application/json': components['schemas']['UpdateUserRequest'];
				};
			};
			responses: {
				/** @description Returns updated user information */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['UserResponse'];
					};
				};
				/** @description If the request is invalid */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description If the user is not authenticated */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		trace?: never;
	};
	'/api/auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Authenticates a user and returns JWT tokens.
		 *     Tokens are always returned in the response body. When useCookies is true, tokens are also set as HttpOnly cookies.
		 */
		post: {
			parameters: {
				query?: {
					/** @description When true, sets tokens in HttpOnly cookies for web clients. Defaults to false (stateless). */
					useCookies?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The login credentials */
			requestBody: {
				content: {
					'application/json': components['schemas']['LoginRequest'];
				};
			};
			responses: {
				/** @description Returns authentication tokens (optionally also set in HttpOnly cookies) */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AuthenticationResponse'];
					};
				};
				/** @description If the credentials are improperly formatted */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
				/** @description If the credentials are invalid */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Refreshes the authentication tokens using a refresh token.
		 *     For web clients, the refresh token is read from cookies. For mobile/API clients, pass it in the request body.
		 *     When useCookies is true, new tokens are also set as HttpOnly cookies.
		 */
		post: {
			parameters: {
				query?: {
					/** @description When true, sets tokens in HttpOnly cookies for web clients. Defaults to false (stateless). */
					useCookies?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Optional request body containing the refresh token (for mobile/API clients) */
			requestBody?: {
				content: {
					'application/json': null | components['schemas']['RefreshRequest'];
				};
			};
			responses: {
				/** @description Returns new authentication tokens (optionally also set in HttpOnly cookies) */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['AuthenticationResponse'];
					};
				};
				/** @description If the refresh token is invalid, expired, or missing */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Logs out the current user by clearing authentication cookies */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Successfully logged out */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/auth/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Registers a new user account */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description The registration details */
			requestBody: {
				content: {
					'application/json': components['schemas']['RegisterRequest'];
				};
			};
			responses: {
				/** @description User successfully created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['RegisterResponse'];
					};
				};
				/** @description If the registration data is invalid */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['ErrorResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * @description Response containing authentication tokens for API clients.
		 *     Web clients can ignore this response body as tokens are also set in HttpOnly cookies.
		 */
		AuthenticationResponse: {
			/**
			 * @description The JWT access token for Bearer authentication.
			 *     Include this in the Authorization header as "Bearer {accessToken}" for subsequent API requests.
			 */
			accessToken?: string;
			/**
			 * @description The refresh token for obtaining new access tokens.
			 *     Use this with the /api/auth/refresh endpoint when the access token expires.
			 */
			refreshToken?: string;
		};
		/** @description Response DTO for error information. */
		ErrorResponse: {
			/** @description The main error message. */
			message?: null | string;
			/** @description Additional error details or technical information. */
			details?: null | string;
		};
		/** @description Represents a user login request with credentials. */
		LoginRequest: {
			/** @description The username for authentication. */
			username: string;
			/** @description The password for authentication. */
			password: string;
		};
		ProblemDetails: {
			type?: null | string;
			title?: null | string;
			/** Format: int32 */
			status?: null | number;
			detail?: null | string;
			instance?: null | string;
		};
		/**
		 * @description Request to refresh authentication tokens using a refresh token.
		 *     For web clients using cookies, this request body is optional.
		 *     For mobile/API clients, the refresh token must be provided in the request body.
		 */
		RefreshRequest: {
			/**
			 * @description The refresh token obtained from a previous login or refresh response.
			 *     Required for mobile/API clients. Optional for web clients (will fall back to cookie).
			 */
			refreshToken?: null | string;
		};
		/** @description Represents a request to register a new user account. */
		RegisterRequest: {
			/** @description The email address for the new account. */
			email: string;
			/** @description The password for the new account. */
			password: string;
			/** @description The phone number for the new account. */
			phoneNumber?: null | string;
			/** @description The first name of the user. */
			firstName?: null | string;
			/** @description The last name of the user. */
			lastName?: null | string;
		};
		/** @description Represents the response returned after successful user registration. */
		RegisterResponse: {
			/**
			 * Format: uuid
			 * @description The unique identifier of the newly created user.
			 */
			id?: string;
		};
		/** @description Represents a request to update the user's profile information. */
		UpdateUserRequest: {
			/** @description The first name of the user. */
			firstName?: null | string;
			/** @description The last name of the user. */
			lastName?: null | string;
			/** @description The phone number of the user. */
			phoneNumber?: null | string;
			/** @description A short biography or description of the user. */
			bio?: null | string;
			/**
			 * Format: uri
			 * @description The URL to the user's avatar image.
			 */
			avatarUrl?: null | string;
		};
		/** @description Represents the current user's information. */
		UserResponse: {
			/**
			 * Format: uuid
			 * @description The unique identifier of the user.
			 */
			id?: string;
			/** @description The username of the user (same as email). */
			username?: string;
			/** @description The email address of the user (same as username). */
			email?: string;
			/** @description The first name of the user. */
			firstName?: null | string;
			/** @description The last name of the user. */
			lastName?: null | string;
			/** @description The phone number of the user. */
			phoneNumber?: null | string;
			/** @description A short biography or description of the user. */
			bio?: null | string;
			/** @description The URL to the user's avatar image. */
			avatarUrl?: null | string;
			/** @description The roles assigned to the user. */
			roles?: string[];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
