/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/Auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['LoginRequest'];
					'text/json': components['schemas']['LoginRequest'];
					'application/*+json': components['schemas']['LoginRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'text/plain': components['schemas']['ProblemDetails'];
						'application/json': components['schemas']['ProblemDetails'];
						'text/json': components['schemas']['ProblemDetails'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'text/plain': components['schemas']['ProblemDetails'];
						'application/json': components['schemas']['ProblemDetails'];
						'text/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/Auth/refresh': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'text/plain': components['schemas']['ProblemDetails'];
						'application/json': components['schemas']['ProblemDetails'];
						'text/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/Auth/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/Auth/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'text/plain': components['schemas']['MeResponse'];
						'application/json': components['schemas']['MeResponse'];
						'text/json': components['schemas']['MeResponse'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'text/plain': components['schemas']['ProblemDetails'];
						'application/json': components['schemas']['ProblemDetails'];
						'text/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/Auth/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					'application/json': components['schemas']['RegisterRequest'];
					'text/json': components['schemas']['RegisterRequest'];
					'application/*+json': components['schemas']['RegisterRequest'];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'text/plain': components['schemas']['ProblemDetails'];
						'application/json': components['schemas']['ProblemDetails'];
						'text/json': components['schemas']['ProblemDetails'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		LoginRequest: {
			/** @description The username for authentication (email) */
			username: string;
			/** @description The password for authentication */
			password: string;
		};
		MeResponse: {
			/**
			 * Format: uuid
			 * @description The unique identifier of the user
			 */
			id?: string;
			/** @description The username of the user */
			username?: string;
			/** @description The roles assigned to the user */
			roles?: string[];
		};
		ProblemDetails: {
			type?: null | string;
			title?: null | string;
			/** Format: int32 */
			status?: null | number | string;
			detail?: null | string;
			instance?: null | string;
		};
		RegisterRequest: {
			/** @description The email address for the new account */
			email: string;
			/** @description The password for the new account, must be at least 6 characters */
			password: string;
			/** @description The phone number for the new account (optional), must be a valid European format */
			phoneNumber?: null | string;
			/** @description The first name of the user (optional), maximum 255 characters */
			firstName?: null | string;
			/** @description The last name of the user (optional), maximum 255 characters */
			lastName?: null | string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
